### ISSUE TITLE
Converting from Json to XML fails for SAR

### ISSUE THREAD

**Issue by Telos-sa** [usnistgov/oscal-cli#132]
### Describe the bug

When attempting to convert SAR json file into XML, error occurs when converting from json to XML.
Command:
oscal-cli ar convert --to xml /Users/13503/Downloads/SAR.json SAR.xml

Error: 
Skipping unhandled top-level JSON field 'assessment-results'.
java.io.IOException: Failed to find root field 'assessment-plan'.

Error indicates that it may be trying to reference the assessment plan instead of the assessment results.  

### Who is the bug affecting

Anytime running the oscal-cli to convert a SAR.  

### What is affected by this bug

Tooling & API

### How do we replicate this issue

Generate a json SAR.  Use the oscal-cli to convert from json to xml.  

### Expected behavior (i.e. solution)

Conversion from SAR.json to SAR.xml

**Comment by Telos-sa** [comment]
Sure thing, I will take a look and see if it is sorted.


Lacy


Stephanie Lacy | Senior Solutions Architect

***@***.*** | www.telos.com<http://www.telos.com/>

[signature_19392405]



________________________________
From: A.J. Stein ***@***.***>
Sent: Monday, April 17, 2023 2:09 PM
To: usnistgov/oscal-cli
Cc: Telos Solutions Architects; Author
Subject: [Caution: External] Re: [usnistgov/oscal-cli] Converting from Json to XML fails for SAR (Issue #132)


This was addressed in #96<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_usnistgov_oscal-2Dcli_issues_96&d=DwMCaQ&c=fwF34uzOsSLA_QyctP8xMw&r=pfbmGckWtc_qcwAJ-keRNhRhyEJgJRmWabzEn4YEDpk&m=BgbSojI3l8lTCowFGU_hROKb1eMLuWwCwmoGT0AqlA-AdYLT5mYJGmZ2xL5HMz8T&s=NiQrxIkeS_K5L-fdh4afLXe9CFq5lvclHor1tOlKldk&e=> but apologies for the delays. I am currently trying to forward a pre-release (SNAPSHOT in Maven terms) into a full release as of Friday and this morning. In the meantime, you can very this bug is fixed with the pre-release here?

https://oss.sonatype.org/content/repositories/snapshots/gov/nist/secauto/oscal/tools/oscal-cli/cli-core/0.3.3-SNAPSHOT/<https://urldefense.proofpoint.com/v2/url?u=https-3A__oss.sonatype.org_content_repositories_snapshots_gov_nist_secauto_oscal_tools_oscal-2Dcli_cli-2Dcore_0.3.3-2DSNAPSHOT_&d=DwMCaQ&c=fwF34uzOsSLA_QyctP8xMw&r=pfbmGckWtc_qcwAJ-keRNhRhyEJgJRmWabzEn4YEDpk&m=BgbSojI3l8lTCowFGU_hROKb1eMLuWwCwmoGT0AqlA-AdYLT5mYJGmZ2xL5HMz8T&s=UyFg3Vpx1FNniUs1Auzn3AiDjAf1liS3Yqr4DMSitsA&e=>

**Comment by Telos-sa** [comment]
Hey Aj,


Just tested, and the issue persists.

This is the package I selected:

cli-core-0.3.3-20230417.145857-15-oscal-cli.zip<https://oss.sonatype.org/content/repositories/snapshots/gov/nist/secauto/oscal/tools/oscal-cli/cli-core/0.3.3-SNAPSHOT/cli-core-0.3.3-20230417.145857-15-oscal-cli.zip> Mon Apr 17 14:59:30 UTC 2023    24976576




Here are the commands, to validate process.


mkdir oscal-cli

cd oscal-cli

unzip /Users/13503/Downloads/cli-core-0.3.3-20230417.145857-15-oscal-cli.zip

cd ..

vi .bash_profile

source .bash_profile

oscal-cli --help

oscal-cli ar convert --to xml /Users/13503/Downloads/SAR.json SAR.xml

unalias oscal-cli

alias

oscal-cli --help

rm -rf .m2

oscal-cli

oscal-cli ar convert --help

oscal-cli ar convert --to xml /Users/13503/Downloads/SAR.json SAR.xml


This is the error

Skipping unhandled top-level JSON field 'assessment-results'.

java.io.IOException: Failed to find root field 'assessment-plan'.


Should I choose a different package?



Stephanie Lacy | Senior Solutions Architect

***@***.*** | www.telos.com<http://www.telos.com/>

[signature_19392405]



________________________________

**Comment by aj-stein-nist** [comment]
That's ... odd. Let me test locally and see if the wrong build was uploaded. But that was the whole point of this release and I thought I verified this with another community contributor recently. So can you pull down develop branch of this repo and try the following?

```
cd path/to/git/repos
https://github.com/usnistgov/oscal-cli.git -b develop # The last part is important.
cd oscal-cli
git submodule update --init --recursive
mvn clean install # You'll need a recent version of Maven for this important part.
# To run on Linux:
./cli-core/target/cli-core-0.3.3-oscal-cli/bin/oscal-cli ar convert --to xml /Users/13503/Downloads/SAR.json SAR.xml
# To run on Windows:
cli-core/target/cli-core-0.3.3-oscal-cli/bin/oscal-cli.bat ar convert --to xml /Users/13503/Downloads/SAR.json SAR.xml

```

**Comment by Telos-sa** [comment]
Same issue.


Here is the code.  Still had to unzip the before using the cli.


git clone --recurse-submodules https://github.com/usnistgov/oscal-cli.git -b develop
cd oscal-cli
git submodule update --init --recursive
mvn clean install
./cli-core/target/cli-core-0.3.3-oscal-cli/bin/oscal-cli --help
(NO SUCH FILE - have to unzip it)
cd cli-core/target/
unzip cli-core-0.3.3-SNAPSHOT-oscal-cli.zip
cd cli-core-0.3.3-SNAPSHOT-oscal-cli/bin
oscal-cli ar convert --help
oscal-cli ar convert --to xml /home/ec2-user/SAR.json SAR.xml

oscal-cli ar convert --to xml /home/ec2-user/CoalFire_SAR.json SAR.xml
Skipping unhandled top-level JSON field 'assessment-results'.
java.io.IOException: Failed to find root field 'assessment-plan'.





Stephanie Lacy | Senior Solutions Architect

***@***.*** | www.telos.com<http://www.telos.com/>

[signature_19392405]



________________________________
From: A.J. Stein ***@***.***>
Sent: Monday, April 17, 2023 3:18 PM
To: usnistgov/oscal-cli
Cc: Telos Solutions Architects; Author
Subject: [Caution: External] Re: [usnistgov/oscal-cli] Converting from Json to XML fails for SAR (Issue #132)


That's ... odd. Let me test locally and see if the wrong build was uploaded. But that was the whole point of this release and I thought I verified this with another community contributor recently. So can you pull down develop branch of this repo and try the following?

cd path/to/git/repos
https://github.com/usnistgov/oscal-cli.git -b develop # The last part is important.
cd oscal-cli
git submodule update --init --recursive
mvn clean install # You'll need a recent version of Maven for this important part.
# To run on Linux:
./cli-core/target/cli-core-0.3.3-oscal-cli/bin/oscal-cli ar convert --to xml /Users/13503/Downloads/SAR.json SAR.xml
# To run on Windows:
cli-core/target/cli-core-0.3.3-oscal-cli/bin/oscal-cli.bat ar convert --to xml /Users/13503/Downloads/SAR.json SAR.xml

**Comment by aj-stein-nist** [comment]
OK, it seems I caused some build weirdness and inappropriately shifted some commits. Can you test this snapshot release?

https://oss.sonatype.org/content/repositories/snapshots/gov/nist/secauto/oscal/tools/oscal-cli/cli-core/0.3.3-SNAPSHOT/cli-core-0.3.3-20230417.204512-18-oscal-cli.zip

Also, now that I found where I made some of those mistakes in the develop branch, updated it, fixed the release tag, and pushed out the release. There is a release notification forthcoming. #108 and #96 have associated unit tests that run during the build, thus I scratched my head.

Thanks for calling this discrepancy out at exactly the correct time! :-)

**Comment by aj-stein-nist** [comment]
OK, release out, sorry for the delays on this too everyone involved. Feel free to reopen.

https://github.com/usnistgov/oscal-cli/releases/tag/v0.3.3
