### ISSUE TITLE
Is instance document validation based on oscal-version?

### ISSUE THREAD

**Issue by GaryGapinski** [usnistgov/oscal-cli#172]
Is instance document validation by `oscal-cli` determined by the `metadata/oscal-version` value within the instance document?

The question arises because an instance document may or may not employ schema association, and even if it does, `oscal-version` seems paramount (i.e., the only assured way to choose an OSCAL schema for validation).

There are, of course, always multiple extant versions of OSCAL employed by OSCAL instance documents.

**Comment by aj-stein-nist** [comment]
Sorry for the delayed reply, @GaryGapinski. At this time, the model classes resulting from code generation from metaschema-java and liboscal-java with a specific version of the OSCAL models as embedded in liboscal-java's OSCAL submodule in the `./oscal` path determine the version of OSCAL validated, not the metadata element in question.

I hope that clarifies, even if the answer is less than satisfactory.
