### ISSUE TITLE
Profile resolution does not include `<value>` elements

### ISSUE THREAD

**Issue by GaryGapinski** [usnistgov/oscal-cli#32]
When the attached profiles are resolved, no `<value>` elements are present in the output catalog. Is this because of the `<set-parameter class="ODP">`?

[pr.zip](https://github.com/usnistgov/oscal-cli/files/9132183/pr.zip) contains the example profiles.

**Comment by david-waltermire-nist** [comment]
Addressed by usnistgov/liboscal-java#56.
