### ISSUE TITLE
Allow converting from and to same format

### ISSUE THREAD

**Issue by mruge** [usnistgov/oscal-cli#43]
# User Story:

Allow the convert functions to convert FROM and TO the same format.  from XML to XML etc.  The function would serve to ensure that input is cosmetically consistent.

## Goals:

In the following example

```
oscal-cli catalog convert --overwrite --to xml input.json one.xml 
oscal-cli catalog convert --overwrite --to xml one.xml    two.xml 
```
Both `one.xml` and `two.xml` should be identical

## Dependencies:

N/A

## Acceptance Criteria

- [ ] All website and readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
@mruge Makes sense. 

In the mean time you can pipe a conversion to any other format and then the original format. lol
