### ISSUE TITLE
XML validation error on 0.3.1

### ISSUE THREAD

**Issue by bryaneaton** [usnistgov/oscal-cli#70]
# Describe the bug

XML validation error `src-resolve: Cannot resolve the name 'DateTimeDatatype' to a(n) 'type definition' component'                                                                                    

# Who is the bug affecting?

# What is affected by this bug?
Validation of a catalog xml seems to fail.

# When does this occur?

When oscal-cli version 0.3.1 is executed either directly or in a container. 

# How do we replicate the issue?
clone repo: `git clone https://github.com/bryaneaton/oscal-cli.git`
build image: `cd oscal-cli; docker build -t oscal-cli:0.3.1;`

Run validate command on oscal-content catalog example: 
`docker run -it -v $PWD:/WORKING oscal-cli:0.3.1 catalog validate basic-catalog.xml`

You should see the following error:
`src-resolve: Cannot resolve the name 'DateTimeDatatype' to a(n) 'type definition' component. `

If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)

I expected a file is valid message or something similar.

**Comment by david-waltermire-nist** [comment]
The cause of this is [liboscal-java](https://github.com/usnistgov/liboscal-java) not being up-to-date with the latest OSCAL. submodule. I'll advance the submodule to address this. Once I release a new liboscal-java version, I'll release a new version of this tool.

**Comment by aj-stein-nist** [comment]
FedRAMP Automation Team inquired about this during a sync meeting and I pointed them to this issue. /cc @david-waltermire-nist @volpet2014

**Comment by aj-stein-nist** [comment]
> The cause of this is [liboscal-java](https://github.com/usnistgov/liboscal-java) not being up-to-date with the latest OSCAL. submodule. I'll advance the submodule to address this. Once I release a new liboscal-java version, I'll release a new version of this tool.

@ThomAPenn and @bryaneaton, I was able to work around this by building my own copy and moving up the OSCAL submodule for the liboscal-java library as a temporary workaround. You will need Maven 3.8.x and a current version of the JDK 11.x or 17.x toolchain.

```sh
git clone https://github.com/usnistgov/metaschema-java.git
git clone https://github.com/usnistgov/liboscal-java.git
git clone https://github.com/usnistgov/oscal-cli.git
# Test it works as-is and cache deps
cd metaschema-java
git submodule update --init --recursive
mvn clean install
cd ..
cd liboscal-java
git submodule update --init --recursive
mvn clean install
cd ..
cd oscal-cli
mvn clean install
# If this works, you have a fresh build in cli-core/target/cli-core-0.3.0-oscal-cli.zip, but with old OSCAL submodule
# Now we slide up OSCAL submodule in liboscal-java
cd ..
cd liboscal-java
cd oscal
git fetch --all # update github.com/usnistgov/OSCAL.git
git checkout develop
cd ..
git submodule update --init --recursive
mvn install -nsu # use local snapshots
cd ..
cd oscal-cli
mvn install -nsu # use local snapshots
# Now we have current oscal-cli but with OSCAL submodule in liboscal-java updated
```

With the locally built copy of the library I was unable to repro the `src-resolve: Cannot resolve the name 'DateTimeDatatype' to a(n) 'type definition' component` error.

@david-waltermire-nist let me know if I got this wrong and if I should such troubleshooting docs to Markdown in repo or using the wiki feature of GitHub.

**Comment by ThomAPenn** [comment]
Here are the instructions that I am using...

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by david-waltermire-nist** [comment]
@aj-stein-nist Your build commands look good above. It should result in a updated version of the v0.3.1 build, with updated OSCAL metaschemas.

@ThomAPenn The link you provided appears to be for installing outlook mobile.

**Comment by aj-stein-nist** [comment]
> > > The cause of this is [liboscal-java](https://github.com/usnistgov/liboscal-java) not being up-to-date with the latest OSCAL. submodule. I'll advance the submodule to address this. Once I release a new liboscal-java version, I'll release a new version of this tool.
> > 
> > 
> > @ThomAPenn and @bryaneaton, I was able to work around this by building my own copy and moving up the OSCAL submodule for the liboscal-java library as a temporary workaround. You will need Maven 3.8.x and a current version of the JDK 11.x or 17.x toolchain.
> > ```shell
> > git clone https://github.com/usnistgov/metaschema-java.git
> > git clone https://github.com/usnistgov/liboscal-java.git
> > git clone https://github.com/usnistgov/oscal-cli.git
> > # Test it works as-is and cache deps
> > cd metaschema-java
> > git submodule update --init --recursive
> > mvn clean install
> > cd ..
> > cd liboscal-java
> > git submodule update --init --recursive
> > mvn clean install
> > cd ..
> > cd oscal-cli
> > mvn clean install
> > # If this works, you have a fresh build in ./cli-core/target/cli-core-0.3.0-oscal-cli.zip, but with old OSCAL submodule
> > # Now we slide up OSCAL submodule in liboscal-java
> > cd ..
> > cd liboscal-java
> > cd oscal
> > git fetch --all # update github.com/usnistgov/OSCAL.git
> > git checkout develop
> > cd ..
> > git submodule update --init --recursive
> > mvn install -nsu # use local snapshots
> > cd ..
> > cd oscal-cli
> > mvn install -nsu # use local snapshots
> > # Now we have current oscal-cli but with OSCAL submodule in liboscal-java updated
> > # recent build should be in ./cli-core/target/cli-core-0.3.0-oscal-cli.zip
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > With the locally built copy of the library I was unable to repro the `src-resolve: Cannot resolve the name 'DateTimeDatatype' to a(n) 'type definition' component` error.
> > @david-waltermire-nist let me know if I got this wrong and if I should such troubleshooting docs to Markdown in repo or using the wiki feature of GitHub.
> 
> Thank you, this workaround works fine for me.

FYI, I will test a release and publish it with this fix shortly. I am testing with other users and hit a speed bump and get back to you on this issue with updates.

Thanks for your reply. I greatly appreciate it!

**Comment by aj-stein-nist** [comment]
Workings towards a release this evening and formally Tuesday to resolve this, sorry for the delays. See #100 to those interested.

**Comment by aj-stein-nist** [comment]
@bryaneaton and @ThomAPenn, a 0.3.2 release should be published shortly, hopefully before COB today, to resolve this issue.

**Comment by bryaneaton** [comment]
Fantastic!
