### ISSUE TITLE
Capability to specify output file name to capture validation errors

### ISSUE THREAD

**Issue by volpet2014** [usnistgov/oscal-cli#77]
# User Story:

The current oscal-cli supports specification of an output file when using the convert command but does not support specifying an output file for the validation errors reported when executing a validation.   

## Goals:

The validation output dumps to stderr  and is pipe-able to a file however, for integrating the oscal-cli into automation scripts it would be good to be able to specify an output file when running validations on artifacts.

## Dependencies:

None

## Acceptance Criteria

Ability to run oscal-cli validation of artifact with additional command line parameter for output file.

**Comment by aj-stein-nist** [comment]
@volpet2014 is there something you would need from a dedicated validation output file argument that would not be satisfied by stream redirection, as you alluded to?

I believe this works in Linux and Windows operating systems (from previous experience and operating system documentation):

```sh
oscal-cli ap validate --as=json example_ssp_oscal.json 1> non-error_output_only.log 2> validation_errors.log
```

**Comment by volpet2014** [comment]
Nope - closing ticket as it is not needed.
