### ISSUE TITLE
Path too long when using batch file in Windows

### ISSUE THREAD

**Issue by IvanDrag0** [usnistgov/oscal-cli#8]
Executing oscal-cli.bat in Windows CMD, results in the following error (the error doesn't occur when executing the oscal-cli file in Cygwin):

```
The input line is too long.
The syntax of the command is incorrect.
```

The reason for the error is that due to the CLASSPATH environment variable using the absolute path for each of the jar files in the lib folder. Doing so creates a string that's too long for CMD to process. Instead, the CLASSPATH variable should be changed to `set CLASSPATH=etc;lib\*` (or similar) and the working directory of the batch file should be changed to the root directory (by adding the line `pushd=%~dp0\..` above it).

**Comment by david-waltermire-nist** [comment]
This was fixed by [configuring](https://github.com/usnistgov/oscal-cli/commit/f7621114755d6e9d49ef02fa90f3f9a5d7772c44) use of a wildcard classpath in the executor on Windows.
